### PR TITLE
indexing for exercises chapter

### PR DESCRIPTION
**Pull request by mattboelkins**

### CODE REVIEW

**Comment by mattboelkins** [comment]
Two comments about this PR:

1.  I noticed that “<idx sortby="figure"><tag>figure</tag></idx>” doesn’t generate a top-level link to the section in which “figure” lives.  Shouldn’t it?  This seems to happen any time we index a chapter or section with something that has a <tag>.  When I put 

  <chapter xml:id="basics-ch-exercise">
    <title>Exercises</title>
    <idx sortby="exercise"><tag>exercise</tag></idx>

I don’t get a “Chapter” link to “exercise”

But if I put 

  <chapter xml:id="basics-ch-exercise">
    <title>Exercises</title>
    <idx>exercise</idx>

Then of course I do.

2.  Maybe I shouldn’t be nesting tags, but the sort seems off with:

            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="answer"><tag>answer</tag></h></idx> 
            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="hint"><tag>hint</tag></h></idx>            
            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="solution"><tag>solution</tag></h></idx>

In the index, the tags get sorted in reverse alphabetical order, as seen in this screenshot:

image

**Comment by mattboelkins** [comment]
I noticed that <idx sortby="figure"><tag>figure</tag></idx> doesn’t generate a top-level link to the section in which “figure” lives.  Shouldn’t it?  This seems to happen any time we index a chapter or section with something that has a <tag>.  When I put 

  <chapter xml:id="basics-ch-exercise">
    <title>Exercises</title>
    <idx sortby="exercise"><tag>exercise</tag></idx>

I don’t get a “Chapter” link to “exercise”

But if I put 

  <chapter xml:id="basics-ch-exercise">
    <title>Exercises</title>
    <idx>exercise</idx>

Then of course I do


Maybe I shouldn’t be nesting tags, but the sort seems off with:

            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="answer"><tag>answer</tag></h></idx> 
            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="hint"><tag>hint</tag></h></idx>            
            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="solution"><tag>solution</tag></h></idx>

In the index, the tags get sorted in reverse alphabetical order:

image

**Comment by mattboelkins** [comment]
I noticed that <idx sortby="figure"><tag>figure</tag></idx> doesn’t generate a top-level link to the section in which “figure” lives.  Shouldn’t it?  This seems to happen any time we index a chapter or section with something that has a <tag>. 

When I put 

  <chapter xml:id="basics-ch-exercise">
    <title>Exercises</title>
    <idx sortby="exercise"><tag>exercise</tag></idx>

I don’t get a “Chapter” link to “exercise”

But if I put 

  <chapter xml:id="basics-ch-exercise">
    <title>Exercises</title>
    <idx>exercise</idx>

Then of course I do

Maybe I shouldn’t be nesting tags, but the sort seems off with:

            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="answer"><tag>answer</tag></h></idx> 
            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="hint"><tag>hint</tag></h></idx>            
            <idx><h sortby="exercise"><tag>exercise</tag></h><h sortby="solution"><tag>solution</tag></h></idx>

In the index, the tags get sorted in reverse alphabetical order:

image

**Comment by mattboelkins** [comment]
image

image

**Comment by mitchkeller** [comment]
I think this might be a thing that's fixed in a more updated `mathbook`. Try pulling and recompiling the reference, as I'm (a) getting all of the index entries you weren't and (b) not having the sorting issue.

**Comment by mattboelkins** [comment]
Yes, that did it.  Thanks!

**Pull request merged**
